// src/lib/legal-strategy/analysis/strategy-map.ts
// Phase 7 — §31 — Build the StrategyMap for a case.
//
// CRITICAL — §31 + §32: NO ranking, NO "best/worst" / "winner" / magic
// score. The strategy map lists, per legal issue, every candidate action
// generated by the §21 generator with its full analysis (prerequisites,
// satisfied, missing, evidence, gaps, authorities, counter-authorities,
// timing, limitations). The user — not the engine — chooses.
//
// Pipeline:
//   1. buildCaseState(caseId) → bounded verified slice.
//   2. buildProceduralPosture(caseId) → stage, court, challenged act.
//   3. For each LegalIssueLink in the CaseState's issues list:
//        a. generateActionCandidates(caseId, posture, [issueId])
//        b. For each candidate: analyzeAction(candidate, caseState, posture)
//        c. researchNeeded = collectResearchTopicsFromCandidate(candidate)
//   4. Return { caseId, issues: [{ issueId, issueStatement, actions, researchNeeded }] }
//
// Deterministic — no LLM. The Codex multi-action synthesizer (§36) may be
// invoked AFTER this deterministic map is built, but only to reorganize /
// surface the deterministic output — never to invent actions or deadlines.

import type { LegalActionCandidate, ProceduralPosture, StrategyMap, StrategyIssueEntry } from "../types";
import { buildCaseState, type CaseState } from "../state/case-state";
import { buildProceduralPosture } from "../state/procedural-posture";
import { generateActionCandidates } from "../actions/candidate-generator";
import { analyzeAction } from "./action-analysis";

// ---------------------------------------------------------------------------
// research-topic collector
// ---------------------------------------------------------------------------

/**
 * Collect "research needed" topics for an issue. These are surfaced to the
 * user as next-step research — they are NOT action recommendations (§17 —
 * the engine does not choose for the user).
 *
 * Topics are derived from the candidate analyses:
 *   - Each UNKNOWN prerequisite → "Verify prerequisite: <description>"
 *   - Each CRITICAL evidence gap → "Obtain document: <requirement>"
 *   - Each DISPUTED prerequisite → "Resolve disputed fact/event: <description>"
 *   - When no supporting authority was found for an action → "Find
 *     supporting authority for action <actionType> under <legalBasis>"
 */
function collectResearchTopics(
  actions: LegalActionCandidate[],
): string[] {
  const topics: string[] = [];
  for (const action of actions) {
    for (const prereq of action.prerequisites) {
      if (prereq.status === "UNKNOWN") {
        topics.push(`Verify prerequisite: ${prereq.description}`);
      } else if (prereq.status === "DISPUTED") {
        topics.push(`Resolve disputed fact/event: ${prereq.description}`);
      }
    }
    for (const gap of action.evidenceGaps) {
      if (gap.severity === "CRITICAL") {
        topics.push(`Obtain document: ${gap.requirement}`);
      }
    }
    if (action.supportingAuthorities.length === 0) {
      topics.push(
        `Find supporting authority for ${action.actionType} under ${action.legalBasis.join(", ")}`,
      );
    }
  }
  // Dedupe.
  return Array.from(new Set(topics));
}

// ---------------------------------------------------------------------------
// buildStrategyMap
// ---------------------------------------------------------------------------

/**
 * Build the StrategyMap for a case.
 *
 * Per §31: lists, per legal issue, every candidate action with its full
 * analysis. NO ranking. NO "best option" / "winner" / magic score.
 *
 * The function is deterministic — no LLM. When the Codex multi-action
 * synthesizer is available (§36), the API route can call this function
 * first, then pass the resulting map to Codex for synthesis/reorganization
 * — but Codex's output must be checked against the same §17/§37 invariants.
 *
 * @param caseId the CaseWorkspace id
 */
export async function buildStrategyMap(caseId: string): Promise<StrategyMap> {
  if (!caseId) {
    return { caseId: "", issues: [] };
  }

  const caseState: CaseState = await buildCaseState(caseId);
  const posture: ProceduralPosture = await buildProceduralPosture(caseId, caseState);

  const issues: StrategyIssueEntry[] = [];
  for (const issue of caseState.issues) {
    const candidates = await generateActionCandidates(
      caseId,
      posture,
      [issue.issueId],
    );
    const analyzedActions: LegalActionCandidate[] = [];
    for (const candidate of candidates) {
      const analyzed = await analyzeAction(candidate, caseState, posture);
      analyzedActions.push(analyzed);
    }
    issues.push({
      issueId: issue.issueId,
      issueStatement: issue.issueStatement,
      actions: analyzedActions,
      researchNeeded: collectResearchTopics(analyzedActions),
    });
  }

  return { caseId, issues };
}
